Update manual.md
Staubgeborener/klipper-backup pull request #87
Opened 2024-03-14 23:53 UTC by kvikindi

Added optional custom message in klipper macro, and show example.

2024-03-15 23:09 UTC, Tylerjet commented
Was this tested locally on your environment as I don't see in the code how the shell command is receiving the Parameters/message.

2024-03-15 23:32 UTC, kvikindi commented
I have indeed ran it in my environment (mainsail OS on raspberry pi zero 2 w).

The idea here is that the shell command only gets the parameters/message if the user types in `MESSAGE="insert message here"`. Otherwise the macro reverts to its previous behaviour, which only starts the shell command (and thus the default commit message as well).

It may not be 100% elegant, but if you run e.g. `UPDATE_GIT "something"` or `UPDATE_GIT PARAMS="something"` in klipper, then all you're getting is `Unknown command: "UPDATE_GIT"` or the default commit message, respectively.

2024-03-15 23:34 UTC, Tylerjet commented
Right but in the actual Bash command where are you passing the params message to it, when you look at your repository commits does it actually have the commit message you used with the macro?

2024-03-15 23:42 UTC, kvikindi commented
It's getting quite late here, but yeah. It works.
![yup](https://github.com/Staubgeborener/klipper-backup/assets/74888286/3a4898df-5e2a-49a9-bc69-36722e729126)

2024-03-16 00:01 UTC, Tylerjet commented
No Problem.

hrmm that is odd i do not see the same output on the latest commit of the repo and i just did a fresh install of it. did you make any local changes to script.sh by chance that were just not pushed to this patch?

![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/49191bb1-2c65-4124-9e80-8397e21beabe)
![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/019c0033-f307-461a-9287-4cac702fd86e)

2024-03-16 09:09 UTC, kvikindi commented
![image](https://github.com/Staubgeborener/klipper-backup/assets/74888286/005f802f-1875-4b44-a8ce-5ae6f2154329)
I think this might be why?

2024-03-16 16:29 UTC, Tylerjet commented
Nah its not that, its setup to still commit even with no changes unless you tell it not to you can see the line just under it with a commit message that was pushed to main

2024-03-17 14:55 UTC, kvikindi commented
My bad.

I was using: `command: bash /home/pi/klipper-backup/script.sh`, where passing the parameters works, whereas with the `command: bash -c "bash $HOME/klipper-backup/script.sh"` it seems to not work.

2024-03-17 19:25 UTC, Tylerjet commented
ahhh ok yeah bash -c is put there because it then allows for $HOME to be used so the user doesn't have to place /home/username there. I think instead of taking out bash -c it should be possible to change how the data is passed.

I'll try a few things and may have some suggested changes

2024-03-17 19:43 UTC, Tylerjet requested changes
This should allow for bash -c to still be used and for the messages to work properly

2024-03-17 19:43 UTC, Tylerjet commented on docs/manual.md
> +        RUN_SHELL_COMMAND CMD=update_git_script PARAMS="{params.MESSAGE}"
```suggestion
        RUN_SHELL_COMMAND CMD=update_git_script PARAMS="'{params.MESSAGE}'"
```

Encapsulate {params.MESSAGE] in single quotes so that spaces are not treated as separate parameters.

2024-03-17 19:43 UTC, Tylerjet commented on docs/manual.md
> +command: bash /home/pi/klipper-backup/script.sh
```suggestion
command: bash -c "bash $HOME/klipper-backup/script.sh $0"
```

use $0 to grab the message instead of relying on script.sh to parse it.

2024-03-17 19:43 UTC, Tylerjet commented on docs/manual.md
> +# replace /home/pi/ with your actual directory.
```suggestion

```

2024-03-17 19:43 UTC, Tylerjet commented on docs/manual.md
> +
```suggestion

```

2024-03-17 20:43 UTC, kvikindi commented
![image](https://github.com/Staubgeborener/klipper-backup/assets/74888286/4b9e40d1-37c8-4134-8599-8f2662d38259)
Nice little bonus feature!

2024-03-17 22:51 UTC, Tylerjet commented
Nice, one last little note is maybe trying to solve the default message as it seems to auto fill with part of the conditional statement.

![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/19c5c9ce-5fa5-4803-b245-9553bdf8d33e)

2024-03-17 23:23 UTC, Tylerjet requested changes
this should resolve what i just mentioned.

2024-03-17 23:23 UTC, Tylerjet commented on docs/manual.md
> +    {% if params.MESSAGE|default("") != "" %}
```suggestion
    {% set message = params.MESSAGE|default() %}
    {% if message %}
```

create a message variable instead that is either the params.MESSAGE or null/empty

2024-03-17 23:23 UTC, Tylerjet commented on docs/manual.md
```suggestion

[gcode_shell_command update_git_script]
command: bash -c "bash $HOME/klipper-backup/script.sh"
timeout: 90.0
verbose: True

```

2024-03-17 23:23 UTC, Tylerjet commented on docs/manual.md
>  [gcode_shell_command update_git_script]
```suggestion
[gcode_shell_command update_git_script_message]
```

2024-03-17 23:23 UTC, Tylerjet commented on docs/manual.md
> +        RUN_SHELL_COMMAND CMD=update_git_script PARAMS="'{params.MESSAGE}'"
```suggestion
        RUN_SHELL_COMMAND CMD=update_git_script_message PARAMS="'{params.MESSAGE}'"
```

2024-03-17 23:55 UTC, merged

2024-03-17 23:55 UTC, Tylerjet commented
Sweet! Has been merged!

2024-03-18 00:05 UTC, kvikindi commented
Awesomeness!
Weirdly enough, I didn't see the unintended default message like you did.
Cheers for this lil' back and forth - I learned a great deal off ye 🤘

2024-03-18 00:07 UTC, Tylerjet commented
Yeah its some specific weirdness and differences between fluidd and mainsail.